FROM microsoft/dotnet:2.2-sdk AS build-env
WORKDIR /app

# copy csproj and restore as distinct layers
COPY Azure-Storage-MSI-ListContainers/*.csproj ./
RUN dotnet restore

#
# copy everything else and build
COPY Azure-Storage-MSI-ListContainers/. ./
RUN dotnet publish -c Release -o out

# build runtime image
FROM microsoft/dotnet:2.2-aspnetcore-runtime AS runtime
WORKDIR /app
COPY --from=build-env /app/out .
ENV ASPNETCORE_URLS http://+:80
EXPOSE 80
ENTRYPOINT ["dotnet", "Azure-Storage-MSI-ListContainers.dll"]